import { query } from './connection.js';

async function seedAttractions() {
  console.log('🌟 Seeding attractions data...');

  const attractions = [
    // New Delhi Attractions (city_id: 1)
    {
      city_id: 1,
      name: 'India Gate',
      description: 'War memorial and iconic landmark',
      category: 'Monument',
      latitude: 28.6129,
      longitude: 77.2295,
      rating: 4.5,
      duration: 60,
      best_time: 'Evening',
      fee: 0,
    },
    {
      city_id: 1,
      name: 'Red Fort',
      description: 'Historic Mughal fortress',
      category: 'Historical Site',
      latitude: 28.6562,
      longitude: 77.241,
      rating: 4.6,
      duration: 180,
      best_time: 'Morning',
      fee: 50,
    },
    {
      city_id: 1,
      name: 'Qutub Minar',
      description: 'Tallest brick minaret in the world',
      category: 'Monument',
      latitude: 28.5244,
      longitude: 77.1855,
      rating: 4.5,
      duration: 120,
      best_time: 'Morning',
      fee: 30,
    },
    {
      city_id: 1,
      name: 'Lotus Temple',
      description: 'Bahai House of Worship',
      category: 'Religious Site',
      latitude: 28.5535,
      longitude: 77.2588,
      rating: 4.7,
      duration: 90,
      best_time: 'Morning',
      fee: 0,
    },
    {
      city_id: 1,
      name: 'Humayuns Tomb',
      description: 'Mughal garden tomb',
      category: 'Monument',
      latitude: 28.5933,
      longitude: 77.2507,
      rating: 4.6,
      duration: 120,
      best_time: 'Morning',
      fee: 30,
    },
    {
      city_id: 1,
      name: 'Akshardham Temple',
      description: 'Modern Hindu temple complex',
      category: 'Religious Site',
      latitude: 28.6127,
      longitude: 77.2773,
      rating: 4.8,
      duration: 180,
      best_time: 'Afternoon',
      fee: 0,
    },
    {
      city_id: 1,
      name: 'Jantar Mantar',
      description: 'Astronomical observatory',
      category: 'Historical Site',
      latitude: 28.6271,
      longitude: 77.2166,
      rating: 4.3,
      duration: 60,
      best_time: 'Morning',
      fee: 25,
    },
    {
      city_id: 1,
      name: 'Rashtrapati Bhavan',
      description: 'Presidential residence',
      category: 'Monument',
      latitude: 28.6142,
      longitude: 77.1996,
      rating: 4.5,
      duration: 90,
      best_time: 'Morning',
      fee: 50,
    },

    // Mumbai Attractions (city_id: 2)
    {
      city_id: 2,
      name: 'Gateway of India',
      description: 'Iconic arch monument',
      category: 'Monument',
      latitude: 18.922,
      longitude: 72.8347,
      rating: 4.5,
      duration: 60,
      best_time: 'Evening',
      fee: 0,
    },
    {
      city_id: 2,
      name: 'Marine Drive',
      description: 'Scenic coastal road',
      category: 'Landmark',
      latitude: 18.9432,
      longitude: 72.8236,
      rating: 4.6,
      duration: 90,
      best_time: 'Evening',
      fee: 0,
    },
    {
      city_id: 2,
      name: 'Elephanta Caves',
      description: 'Ancient rock-cut caves',
      category: 'Historical Site',
      latitude: 18.9633,
      longitude: 72.9315,
      rating: 4.4,
      duration: 240,
      best_time: 'Morning',
      fee: 40,
    },
    {
      city_id: 2,
      name: 'Chhatrapati Shivaji Terminus',
      description: 'Historic railway station',
      category: 'Monument',
      latitude: 18.9398,
      longitude: 72.8355,
      rating: 4.5,
      duration: 60,
      best_time: 'Morning',
      fee: 0,
    },
    {
      city_id: 2,
      name: 'Haji Ali Dargah',
      description: 'Mosque and tomb on an islet',
      category: 'Religious Site',
      latitude: 18.9826,
      longitude: 72.8089,
      rating: 4.4,
      duration: 90,
      best_time: 'Evening',
      fee: 0,
    },
    {
      city_id: 2,
      name: 'Siddhivinayak Temple',
      description: 'Famous Hindu temple',
      category: 'Religious Site',
      latitude: 19.0176,
      longitude: 72.8301,
      rating: 4.6,
      duration: 60,
      best_time: 'Morning',
      fee: 0,
    },
    {
      city_id: 2,
      name: 'Juhu Beach',
      description: 'Popular public beach',
      category: 'Beach',
      latitude: 19.099,
      longitude: 72.8266,
      rating: 4.2,
      duration: 120,
      best_time: 'Evening',
      fee: 0,
    },
    {
      city_id: 2,
      name: 'Sanjay Gandhi National Park',
      description: 'Wildlife park in the city',
      category: 'Nature',
      latitude: 19.2222,
      longitude: 72.9115,
      rating: 4.5,
      duration: 240,
      best_time: 'Morning',
      fee: 50,
    },

    // Bangalore Attractions (city_id: 3)
    {
      city_id: 3,
      name: 'Lalbagh Botanical Garden',
      description: 'Historic botanical garden',
      category: 'Nature',
      latitude: 12.9507,
      longitude: 77.5848,
      rating: 4.5,
      duration: 120,
      best_time: 'Morning',
      fee: 20,
    },
    {
      city_id: 3,
      name: 'Bangalore Palace',
      description: 'Royal palace with Tudor architecture',
      category: 'Monument',
      latitude: 12.998,
      longitude: 77.592,
      rating: 4.4,
      duration: 120,
      best_time: 'Morning',
      fee: 230,
    },
    {
      city_id: 3,
      name: 'Cubbon Park',
      description: 'Large green space in the city',
      category: 'Nature',
      latitude: 12.9762,
      longitude: 77.5929,
      rating: 4.4,
      duration: 90,
      best_time: 'Morning',
      fee: 0,
    },
    {
      city_id: 3,
      name: 'ISKCON Temple',
      description: 'Modern Krishna temple',
      category: 'Religious Site',
      latitude: 13.0096,
      longitude: 77.5512,
      rating: 4.6,
      duration: 90,
      best_time: 'Evening',
      fee: 0,
    },
    {
      city_id: 3,
      name: 'Tipu Sultan Palace',
      description: 'Historic summer palace',
      category: 'Historical Site',
      latitude: 12.9591,
      longitude: 77.5744,
      rating: 4.2,
      duration: 90,
      best_time: 'Morning',
      fee: 20,
    },
    {
      city_id: 3,
      name: 'Vidhana Soudha',
      description: 'State legislature building',
      category: 'Monument',
      latitude: 12.9795,
      longitude: 77.5908,
      rating: 4.3,
      duration: 60,
      best_time: 'Evening',
      fee: 0,
    },
    {
      city_id: 3,
      name: 'Bull Temple',
      description: 'Ancient Hindu temple',
      category: 'Religious Site',
      latitude: 12.9421,
      longitude: 77.5693,
      rating: 4.4,
      duration: 60,
      best_time: 'Morning',
      fee: 0,
    },
    {
      city_id: 3,
      name: 'Bannerghatta National Park',
      description: 'Biological reserve and zoo',
      category: 'Nature',
      latitude: 12.8005,
      longitude: 77.5768,
      rating: 4.3,
      duration: 240,
      best_time: 'Morning',
      fee: 100,
    },

    // Jaipur Attractions (city_id: 4)
    {
      city_id: 4,
      name: 'Amber Fort',
      description: 'Majestic hilltop fort',
      category: 'Historical Site',
      latitude: 26.9855,
      longitude: 75.8513,
      rating: 4.7,
      duration: 180,
      best_time: 'Morning',
      fee: 100,
    },
    {
      city_id: 4,
      name: 'Hawa Mahal',
      description: 'Palace of Winds',
      category: 'Monument',
      latitude: 26.9239,
      longitude: 75.8267,
      rating: 4.5,
      duration: 90,
      best_time: 'Morning',
      fee: 50,
    },
    {
      city_id: 4,
      name: 'City Palace',
      description: 'Royal palace complex',
      category: 'Monument',
      latitude: 26.9255,
      longitude: 75.8237,
      rating: 4.6,
      duration: 150,
      best_time: 'Morning',
      fee: 200,
    },
    {
      city_id: 4,
      name: 'Jantar Mantar',
      description: 'Astronomical observatory',
      category: 'Historical Site',
      latitude: 26.9246,
      longitude: 75.8243,
      rating: 4.5,
      duration: 90,
      best_time: 'Morning',
      fee: 50,
    },
    {
      city_id: 4,
      name: 'Jal Mahal',
      description: 'Palace in the middle of Man Sagar Lake',
      category: 'Monument',
      latitude: 26.953,
      longitude: 75.8462,
      rating: 4.4,
      duration: 60,
      best_time: 'Evening',
      fee: 0,
    },
    {
      city_id: 4,
      name: 'Nahargarh Fort',
      description: 'Fort overlooking the city',
      category: 'Historical Site',
      latitude: 26.9368,
      longitude: 75.8154,
      rating: 4.5,
      duration: 120,
      best_time: 'Evening',
      fee: 50,
    },
    {
      city_id: 4,
      name: 'Jaigarh Fort',
      description: 'Hilltop fort with cannon foundry',
      category: 'Historical Site',
      latitude: 26.9854,
      longitude: 75.8515,
      rating: 4.4,
      duration: 120,
      best_time: 'Morning',
      fee: 35,
    },
    {
      city_id: 4,
      name: 'Albert Hall Museum',
      description: 'Oldest museum in Rajasthan',
      category: 'Museum',
      latitude: 26.9124,
      longitude: 75.8187,
      rating: 4.3,
      duration: 120,
      best_time: 'Afternoon',
      fee: 40,
    },
  ];

  try {
    for (const attraction of attractions) {
      await query(
        `INSERT INTO attractions (city_id, name, description, category, latitude, longitude, rating, estimated_duration, best_time_to_visit, entry_fee)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
         ON CONFLICT DO NOTHING`,
        [
          attraction.city_id,
          attraction.name,
          attraction.description,
          attraction.category,
          attraction.latitude,
          attraction.longitude,
          attraction.rating,
          attraction.duration,
          attraction.best_time,
          attraction.fee,
        ]
      );
    }
    console.log('✅ Attractions seeded successfully!');
  } catch (error) {
    console.error('❌ Error seeding attractions:', error);
    throw error;
  }
}

seedAttractions()
  .then(() => process.exit(0))
  .catch(() => process.exit(1));
